### ISSUE TITLE
[Bug report] 로컬 서버 페이지 네비게이션 레이아웃 깨짐

### ISSUE THREAD

**Issue by wSeungMi** [javascript-tutorial/ko.javascript.info#1568]
## 🐛 Bug report
![서버에러](https://user-images.githubusercontent.com/104605709/190060344-c87b2a45-5c1e-4dfc-a0d7-81742cc84bd2.png)

로컬 서버 실행 시 상세 페이지 네비게이션 레이아웃이 깨져서 오른쪽 페이지 네비게이션을 제대로 사용할 수 없습니다.

## 예상된 기능 혹은 화면
![서버에러_수정](https://user-images.githubusercontent.com/104605709/190064191-a2f6ba28-ee62-4cb0-8afb-df911c5250e9.png)

정상적인 페이지에서는 페이지 네비게이션이 콘텐츠의 양옆에 위치하고 있어야 합니다.

## 환경

[OS] 맥 m1, [브라우저] 크롬

## 재연할 수 있는 방법

```css
/* 기존 코드 */
.page__nav_next {
     left: 0;
     transition: top .2s;
}
```
```css
/* 수정 코드 */
.page__nav_next {
     right: 0;
     transition: top .2s;
}
```

<a>요소의 클래스 .page__nav_next의 속성을 left에서 right로 변경해주면 배치가 수정되면서 페이지 네비게이션 버튼도 정상적으로 동작됩니다.
